# Generated by Django 5.2.11 on 2026-03-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='logo',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='employer/logos/'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employer/photos/'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='employer/posters/'),
        ),
    ]
