# Generated by Django 5.2.11 on 2026-03-02 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_employerprofile_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.interview')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.seekerprofile')),
            ],
        ),
    ]
